### PR TITLE
configurable multiple etcd endpoints and key name changes in constructor

### PR DESCRIPTION
**Pull request by phaniraj75**
Fix: https://github.com/casbin/etcd-watcher/issues/4

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @phaniraj75 , we use Go Modules instead of glide. Can you re-organize/rework your commits, maybe into one or two final commits?

**Comment by phaniraj75** [comment]
Paradon me, i didn't realized that i filed PR anyways i found couple of more minor discrepencies like import of "github.com/etcd/clientv3" instead of "go.etcd.io/etcd/clientv3", this might cause unintended import of same repo under two different pkg names, I'll rectify this in new PR.

**Comment by hsluoyz** [comment]
Don't need to open a new PR. Just rewrite the commits.

**Comment by phaniraj75** [comment]
There is been some issues i encountered, will update with new pr with changes

**Pull request closed without merging**
