### PR TITLE
configurable watcher with multiple endpoints

### PR DESCRIPTION
**Pull request by phaniraj75**
Fix: https://github.com/casbin/etcd-watcher/issues/4

### CODE REVIEW

**Comment by hsluoyz** [comment]
Please make Travis CI pass.

**Comment by phaniraj75** [comment]
Locally all UTs has passed, and i see that historically also builds are failing with same reason "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.". I'll try this with local travis ci engine will attempt to make fix today.

**Comment by hsluoyz** [comment]
The test halts, please fix.

**Comment by phaniraj75** [comment]
Need help on this, i checked in master branch travis report tests are getting halted in the same manner, ran locally all the UTs all the UTs are passed and all go routines are completed the execution.

**Comment by phaniraj75** [comment]
@hsluoyz corrected halting UTs, it was because etcd db was not running and etcd client apis end up waiting forever, i made the travis.ci changes to have etcd docker up and running prior to run of the tests.

**Comment by hsluoyz** [comment]
lgtm

**Comment by hsluoyz** [comment]
@phaniraj75 great work!

**Pull request merged**
