### PR TITLE
fix: remove useless log prints

### PR DESCRIPTION
**Pull request by sasakiyori**
Fix: https://github.com/casbin/etcd-watcher/issues/18

### CODE REVIEW

**Comment by hsluoyz** [comment]
@sasakiyori fix:

image

**Comment by sasakiyori** [comment]
> @sasakiyori fix:
> 
> image

done

**Comment by hsluoyz** [comment]
@sasakiyori you started the title with `chore`, I don't know if it will have a release. If you want a release, plz make a PR starting with `feat` or `fix`

**Comment by sasakiyori** [comment]
@hsluoyz  oh I find that  `semantic-release` actually doesn't trigger the `release` action for `chore`. But pr has been merged, I don't know if it can be remedied... It seems that `semantic-release` is triggered by push action in this repo.

**Comment by hsluoyz** [comment]
@sasakiyori you need to make a new fix prefix PR, like fixing a typo or what

**Pull request merged**
